name: Lint

on:
  pull_request:
permissions:
  contents: read       # Required to checkout the code
  statuses: write      # Required for Super-Linter to post the "Success/Failure" checkmark

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Important for Super-Linter to see full history

      - name: super linter
        uses: step-security/super-linter/slim@v8
        env:
          # This line fixes the "unbound variable" crash
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
